### ISSUE TITLE
Can this be deployed on existing proxmox with Ceph without ZFS?

### ISSUE THREAD

**Issue by uhlhosting** [zimmertr/TKS#20]
Is this setup will work on a proxmox ceph cluster?

**Comment by zimmertr** [comment]
TKS is a collection of my personal IAC/CAC for deploying K8s and other cloud native software and apps into my homelab. It's an ever-evolving project that is based on my current curiosity and hardware. Right now, everything as written assumes the use of ZFS. That being said, nothing _requires_ the use of ZFS. And nothing _prevents_ the use of ceph. You just might have to tweak things a bit. 

Here are some areas I think you might need to tweak things.

1) Block/File Storage is used by [TKS-Bootstrap_Kubernetes](https://github.com/zimmertr/TKS-Bootstrap_Kubernetes) to run virtual machines on Proxmox. Virtual Machines are provisioned using Telmate's Terraform provider [here](https://github.com/zimmertr/TKS-Bootstrap_Kubernetes/search?q=TKS_STORAGE). The Terraform provider documents the use of the Storage argument in the provider [here](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resources/vm_qemu.md#disk-block). Since the Terraform providers currently receive the values for these arguments via the variables `TKS_STORAGE` and `TKS_STORAGE_TYPE` you probably just have to set them according to the values shown [here](https://pve.proxmox.com/wiki/Storage) and hope that the Terraform provider supports it. It probably will but it's not officially maintained by Proxmox so your results may vary. 

2) Should you choose to stand up the monitoring stack using [TKS-Bootstrap_Grafana](https://github.com/zimmertr/TKS-Deploy_Grafana/search?q=GRAFANA_STORAGE) you will similarly have to set the `GRAFANA_STORAGE` and `GRAFANA_STORAGE_TYPE` variables according to your environment. 

3) With respect to Kubernetes, TKS doesn't force you to use any type of backing Storage Class for your data. I personally export my ZFS pool as a NFS server and then map Persistent Volumes to it using [this](https://github.com/zimmertr/TKS-Deploy_Kubernetes_Apps/tree/master/NFS-Provisioner) operator. In your case, you'll probably want to explore using [Rook with Ceph](https://rook.io/docs/rook/v1.5/ceph-storage.html). After which if you define a default storage class the rest of the Kustomize & Ansible projects defined for [TKS-Deploy_Kubernetes_Apps](https://github.com/zimmertr/TKS-Deploy_Kubernetes_Apps) should be able to provision PVs and PVCs out of the box. This is the beauty of Kubernetes & the infrastructure abstractions it affords us :)  


The [TKS-Bootstrap_Proxmox](https://github.com/zimmertr/TKS-Bootstrap_Proxmox) repo may make things look incompatible because I am leveraging ZFS & hardware RAIDs. But please understand these are not **hard** requirements. Just examples of how I do things. They can effectively be skipped over as long as you set the variables properly in 1 & 2 above. 

I hope this helps, please let me know how things go for you. I'll leave this open for now and close with the assumption things work if I don't hear back from you.

**Comment by zimmertr** [comment]
Closing due to lack of followup.....
